{"error": null, "issues": [{"address": 162, "code": "vault.transfer(msg.value)", "contract": "unknown", "debug": "SOLVER OUTPUT:\ncall_value: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_unknown[0]: 0x9f1dcd5600000000000000000000000000000000000000000000000000000000\ncalldatasize_unknown: 0x4\n", "description": "In the function `fallback` a non-zero amount of Ether is sent to an address taken from function arguments.\nIt seems that this function can be called without restrictions.", "filename": "contracts/0x2c793ecf55c53a149a76e895dcb335da47e46526_PasserBy.sol", "function": "fallback", "lineno": 21, "title": "Ether send", "type": "Warning"}], "success": true}
